language: node_js

install:
  - npm i

script:
  - npm run lint
  - npm run coverage

branches:
  only:
    - master
    - develop

after_script:
  - npm run coverage:report
  - npm run coverage:clear
